import gql from 'graphql-tag'

// Query for feed of the screen (Paginated)
export const GET_ROOM_FEED = gql`
    query get_room_posts($limit:Int!, $room_post_cursor:String){
        get_room_posts_user_id(user_input:{limit:$limit, room_post_cursor:$room_post_cursor}){
            room_posts{
                _id, 
                creator_id,
                creator_info{
                    user_id, 
                    username,
                    avatar{
                        width,
                        height,
                        cdn_url,
                        image_name
                    },
                    three_words,
                    default_avatar
                },
                likes_count,
                user_liked, 
                image{
                    width,
                    height,
                    cdn_url,
                    image_name
                }, 
                description,
                timestamp,
                post_type,
                room_objects{
                    _id,
                    name,
                    timestamp
                },
                caption_objects{
                    _id,
                    post_id,
                    creator_info{
                        user_id, 
                        username,
                        avatar{
                            width,
                            height,
                            cdn_url,
                            image_name
                        },
                        three_words,
                        default_avatar
                    },
                    timestamp,
                    last_modified,
                    description,
                    up_votes_count, 
                    down_votes_count,
                    user_vote_object{
                        _id, 
                        content_id, 
                        vote_type
                    },
                    is_user
                },
                is_user
            },
            next_page,
            room_post_cursor, 
            last_room_post_cursor            
        }
    }
` 


export const GET_ROOM_POSTS = gql`
    query get_room_post($room_id:ID!, $limit:Int!, $room_post_cursor:String){
        get_room_posts_room_id(user_input:{
            room_id:$room_id,
            limit:$limit,
            room_post_cursor:$room_post_cursor
        }),{
            room_posts{
                _id, 
                creator_id,
                creator_info{
                    user_id, 
                    username,
                    avatar{
                        width,
                        height
                        cdn_url,
                        image_name
                    },
                    three_words,
                    default_avatar
                },
                likes_count,
                user_liked, 
                image{
                    width,
                    height,
                    cdn_url,
                    image_name
                }, 
                description,
                timestamp,
                post_type,
                room_objects{
                    _id,
                    name,
                    timestamp
                },
                caption_objects{
                    _id,
                    post_id,
                    creator_info{
                        user_id, 
                        username,
                        avatar{
                            width,
                            height,
                            cdn_url,
                            image_name
                        },
                        three_words,
                        default_avatar
                    },
                    timestamp,
                    last_modified,
                    description,
                    up_votes_count, 
                    down_votes_count,
                    user_vote_object{
                        _id, 
                        content_id, 
                        vote_type
                    },
                    is_user
                },
                is_user
            },
            next_page,
            room_post_cursor, 
            last_room_post_cursor            
        }
    }
`

export const GET_USER_PROFILE_POSTS = gql`
    query get_user_profile_post($limit:Int!, $room_post_cursor:String, $user_id:ID){
        get_user_profile_posts(user_input:{limit:$limit, room_post_cursor:$room_post_cursor, user_id:$user_id}){
            room_posts{
                _id, 
                creator_id,
                creator_info{
                    user_id, 
                    username,
                    avatar{                    
                        width,
                        height,
                        cdn_url,
                        image_name
                    },
                    three_words,
                    default_avatar
                },
                likes_count,
                user_liked, 
                image{
                    width,
                    height,
                    cdn_url,
                    image_name
                }, 
                description,
                timestamp,
                post_type,
                room_objects{
                    _id,
                    name,
                    timestamp
                },
                caption_objects{
                    _id,
                    post_id,
                    creator_info{
                        user_id, 
                        username,
                        avatar{
                            width,
                            height,
                            cdn_url,
                            image_name
                        },
                        three_words,
                        default_avatar
                    },
                    timestamp,
                    last_modified,
                    description,
                    up_votes_count, 
                    down_votes_count,
                    user_vote_object{
                        _id, 
                        content_id, 
                        vote_type
                    },
                    is_user
                },
                is_user
            },
            next_page,
            room_post_cursor, 
            last_room_post_cursor,
                   
        }
    }
` 

// Mutations
export const CREATE_ROOM_POST = gql`
    mutation create_room_posts(
        $creator_id:ID!,
        $description:String!, 
        $room_ids:[ID!]!,
        $post_type:String!,
        $image:image_input,
    ){
        create_room_post(user_input:{
            creator_id:$creator_id,
            description:$description,
            room_ids:$room_ids
            post_type:$post_type,
            image:$image
        }),{
            _id, 
            creator_id,
            creator_info{
                user_id, 
                username,
                avatar{
                    width,
                    height,
                    cdn_url,
                    image_name
                },
                three_words,
                default_avatar
            },
            likes_count,
            user_liked, 
            image{
                width,
                height,
                cdn_url,
                image_name
            }, 
            description,
            timestamp,
            post_type,
            room_objects{
                _id,
                name,
                timestamp
            },
            is_user
        }
    }
`


export const DEACTIVATE_ROOM_POST = gql`
    mutation deactivate_room_posts($post_id:ID!){
        deactivate_room_post(post_id:$post_id)
    }
`

export const REPORT_POST = gql`
    mutation report_posts($post_id:ID!, $reason:String!){
        report_post(user_input:{
            post_id:$post_id,
            reason:$reason
        })
    }
`