import {
    Platform
} from "react-native"

export default base_style = {
    color:{
        primary_color:Platform.OS==="ios"?"#000000":'#121212',
        primary_color_lighter:Platform.OS==="ios"?"#1C1C1C":'#1C1C1C',
        secondary_color:"#ffffff",
        icon_not_selected:"#98989d",
        icon_selected:"#FFD600"
    },
    typography:{
        small_header:{
            color:'#ffffff',
            fontSize:17,
            fontWeight:'bold',
        },
        small_font:{
            color:'#ffffff',
            fontSize:17,
        },
        small_font_paragraph:{
            color:'#ffffff',
            fontSize:17,
            textAlign:'left'
        },
        mini_font:{
            color:"#ffffff",
            fontSize:12,
        },
        medium_header:{
            color:'#ffffff',
            fontSize:22,
            fontWeight:'bold',
        },
        medium_font:{
            color:'#ffffff',
            fontSize:22,
        },
        font_colors:{
            title_text:{
                color:"#ffffff"
            },
            high_emphasis:{
                color:"#ffffff",
            },
            medium_emphasis:{
                color:"#ffffff",
                opacity:0.87
            },
            low_emphasis:{
                color:"#ffffff",
                opacity:0.60
            },
            disabled:{
                color:"#ffffff",
                opacity:0.38
            },
            text_input_placeholder:"#999999"
        }
    },
    icons:{
        icon_size:25
    }
}
