export default base_style = {
    color:{
        primary_color:'#121212',
        primary_color_lighter:'#2c2c2c',
        secondary_color:"#ffffff"
    },
    typography:{
        small_header:{
            color:'#ffffff',
            fontSize:17,
            fontWeight:'bold',
        },
        small_font:{
            color:'#ffffff',
            fontSize:17,
        },
        small_font_paragraph:{
            color:'#ffffff',
            fontSize:17,
            textAlign:'left'
        },
        mini_font:{
            color:"#ffffff",
            fontSize:12,
        },
        medium_header:{
            color:'#ffffff',
            fontSize:22,
            fontWeight:'bold',
        },
        medium_font:{
            color:'#ffffff',
            fontSize:22,
        }
    }
}
