# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      #match(app_identifier: 'org.2020.Tornado', type: 'development', readonly: true)
      match(type: 'appstore', readonly: true)
    end
  desc 'Build the iOS application.'
    private_lane :build do
      certificates
      increment_build_number
      gym(scheme: 'tornado', workspace: 'tornado.xcworkspace')
    end
  desc 'Ship to Testflight.'
    lane :beta do
      build
      pilot
    end
end
